---
title: "ShellSIM growth model"
author: "Mariano Viz"
date: "23/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```




```{r}
#Net energy balance function for C. gigas (intitally only considering CHL - i.e., without taking into account POM and POC and, therefore, REMORG, EREM, and NIRREMORG)

net_energy_balance <- function(CHL, NIRREMORG = 0, EREM = 0, TEMP, WE = 1, WS = 1, MNEA = 1350) {
  
  selorg = (CHL*50)/0.38
  nirselorg = (-0.33+(4.11*selorg)) #check table 2 --> TEF and (WE/WS)^0.62
  nea = (((nirselorg*23.5)+(NIRREMORG*0.15*EREM))*0.8*24)
  cr = 0.32+(0.323*TEMP)+(-.011*(TEMP)^2)
  tef = cr/(0.32+(0.323*15)+(-.011*(15)^2)) #check table 2 and check TEM (p.242)!!
  mhl = 4.005*tef*((WE/WS)^0.72) #we/ws???
  thl = mhl + (0.23*nea)
  ON = 10 + (((200-10)/MNEA)*nea)
  el = (((thl/14.06)/16)/ON)*14*1000*24
  neb = nea-thl-(el*0.02428)
  
  
  return(neb)
}

net_energy_balance(CHL =0.002, TEMP = 12)
net_energy_balance(CHL =0, TEMP = 12)

#CHL in mg/l!

#I'll try to incorporate the other equatins and the dynamics. Once is working I'll copy it in an RScrip, annotate and put it into a subdirectory called R (as if we were going to create a package - thing that we can easily do if it works).

```



```{r}
#Shell length equation:

net_energy_balance(CHL =0.004, TEMP = 12)

shell_length <- function(initial_length, neb, days, MTA = 0.76, ECS = 0.161, a = 2.767, b = 0.827) {
  time = days/365
  initial_DSW = (initial_length/a)^(1/b)
  SG = (1-MTA)*neb
  total_shell_energy = SG*time
  DSW = initial_DSW + (SG/(ECS*1000)*time)
  SL = a*DSW^b
  return(SL)
}



shell_length(1, 577.3028, 100)


days<- seq(1, 730, length.out=730)

shell_df <- data.frame(initial_length = 1, neb = 577.3028, days = days, shell_length = NA)

shell_df$shell_length <- shell_length(shell_df$initial_length, shell_df$neb, shell_df$days)

ggplot(data = shell_df, aes(x= days, y = shell_length))+
  geom_line()

# Need to add the restriction variable: Effects of Shellfish Size!

```




```{r}
# Value of information example:

profits = function(E,X, a=1, b=0.1)
{
  profits = a*E*X - b*(X^2)/E
  return(profits)
}

# a = 1
# b = .1
# Elo = 1
# Ehi = 2


# X is the choice (like stocking density)
# E is the environmental variable (like temperature) -- use values around 1 or 2
# Try to find the value of information for this example!



E_norm <- rnorm(mean = 1.5, sd = 0.3, n = 100)
X_lo <- seq(0, 10, length.out=100)
X_hi <- seq(0, 40, length.out=100)
X_norm<- seq(0, 22.5, length.out=100)

profits_lo_df <- data.frame(E_lo = 1, X_lo = X_lo, profits = NA)
profits_hi_df <- data.frame(E_hi = 2, X_hi = X_hi, profits = NA)
profits_norm_df <- data.frame(E_norm = E_norm, X_norm = X_norm, profits = NA)

profits_lo_df$profits <- profits(profits_lo_df$E_lo, profits_lo_df$X_lo)
profits_hi_df$profits <- profits(profits_hi_df$E_hi, profits_hi_df$X_hi)
profits_norm_df$profits <- profits(profits_norm_df$E_norm, profits_norm_df$X_norm)

ggplot()+
  geom_line(data = profits_lo_df, aes(x= X_lo, y=profits))+
  geom_line(data = profits_hi_df, aes(x= X_hi, y=profits))+
  theme_minimal() +
  labs(x = "Choice (X)",
       y = "Profits")


## Profits of optimal info:
# Optimal X_lo = 5: TT=2.5
optimal_lo <- profits(E=1, X=5)
#Optimal X_hi = 20: TT=20
optimal_hi <- profits(E=2, X=20)

#Average X E_lo:
not_optimal_lo <- profits(E=1, X=12.5)
#Average X E_hi:
not_optimal_hi <- profits(E=2, X=12.5)


# prob E_lo = 0.5
p_lo <- 0.5
# prob E_hi = 0.5
p_hi <- 0.5


#Profits optimal: 
profits_optimal <- p_lo*optimal_lo + p_hi*optimal_hi

#Profits NOT optimal: 
profits_not_optimal <- p_lo*not_optimal_lo + p_hi*not_optimal_hi

# Value of information:
value_info <- profits_optimal - profits_not_optimal

value_info

```

## Calcualting the value of information

```{r}

#maximum profit if temperature was correct
max_profit <- max(profits_hi_df$profits) + max(profits_lo_df$profits)

#farmer guesses env. variable will be around 5
guess_profit_high <- profits_hi_df %>% 
                  slice(which.min(abs(X_hi - 5)))
guess_profit_low <- profits_lo_df %>% 
                  slice(which.min(abs(X_lo - 5)))

#total profit from guessing
guess_profit <- guess_profit_high$profits + guess_profit_low$profits

#difference between max and guess profit -- value of information
value_of_information <- max_profit - guess_profit

```















