---
title: "Basic VoI Plots"
author: "Mariano Viz"
date: "01/02/2022"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(janitor)
library(ggpubr)
library(kableExtra)
library(patchwork)

library(extrafont)



data <- read_csv("voi_plots.csv")

nv_1 <- read_csv("1_1.csv")
nv_2 <- read_csv("1_2.csv")
nv_3 <- read_csv("1_3.csv")

l_1 <- read_csv("2_1.csv")
l_2 <- read_csv("2_2.csv")
l_3 <- read_csv("2_3.csv")

h_1 <- read_csv("3_1.csv")
h_2 <- read_csv("3_2.csv")
h_3 <- read_csv("3_3.csv")
```


```{r}
#Font:
library(sysfonts)
font_add_google("Source Sans Pro")

```



# VOI Examples

```{r}

ggplot(data = nv_1, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = nv_2, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = nv_3, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = l_1, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = l_2, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = l_3, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = h_1, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = h_2, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")


ggplot(data = h_3, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")

```






```{r}
nv1 <- ggplot(data = nv_1, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
  geom_point(aes(x=20, y=max(nv_1$prof_1, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_2, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_3, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_4, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_5, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_1, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_2, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_3, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_4, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_5, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
  theme_minimal()+
    theme_minimal()+
    geom_text(aes(x = 95,y = 105, label= paste("VoI: $0", sep = ""), hjust = 0), size = 4, color = "black")+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))




nv2 <- ggplot(data = nv_2, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
  geom_point(aes(x=20, y=max(nv_2$prof_1, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_2, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_3, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_4, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_5, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_1, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_2, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_3, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_4, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_5, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
  theme_minimal()+
    theme_minimal()+
    geom_text(aes(x = 95,y = 105, label= paste("VoI: $0", sep = ""), hjust = 0), size = 4, color = "black")+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))


nv3 <- ggplot(data = nv_3, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
  geom_point(aes(x=20, y=max(nv_3$prof_1, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_2, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_3, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_4, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_5, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_1, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_2, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_3, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_4, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_5, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
  theme_minimal()+
    theme_minimal()+
    geom_text(aes(x = 95,y = 105, label= paste("VoI: $0", sep = ""), hjust = 0), size = 4, color = "black")+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))


#################3



nv11 <- ggplot(data = nv_1, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
    geom_point(aes(x=20, y=max(nv_1$prof_1, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_2, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_3, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_4, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_5, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_1, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_2, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_3, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_4, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_1$prof_5, na.rm=TRUE), xend = 20, yend = max(nv_1$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  theme_minimal()+
    theme_minimal()+
    geom_text(aes(x = 95,y = 105, label= paste("VoI: $0", sep = ""), hjust = 0), size = 4, color = "black")+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))




nv21 <- ggplot(data = nv_2, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
    geom_point(aes(x=20, y=max(nv_2$prof_1, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_2, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_3, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_4, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_5, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_1, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_2, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_3, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_4, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_2$prof_5, na.rm=TRUE), xend = 20, yend = max(nv_2$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    theme_minimal()+
    geom_text(aes(x = 95,y = 105, label= paste("VoI: $0", sep = ""), hjust = 0), size = 4, color = "black")+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))


nv31 <- ggplot(data = nv_3, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
    geom_point(aes(x=20, y=max(nv_3$prof_1, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_2, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_3, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_4, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_5, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_1, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_2, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_3, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_4, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 0, y = max(nv_3$prof_5, na.rm=TRUE), xend = 20, yend = max(nv_3$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01) +
    theme_minimal()+
    geom_text(aes(x = 95,y = 105, label= paste("VoI: $0", sep = ""), hjust = 0), size = 4, color = "black")+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))


    
```




```{r}
# VOI: Horizontal Value

source("R/voi_1.R")
source("R/voi.R")


l_1[is.na(l_1)] <- 0
l_2[is.na(l_2)] <- 0
l_3[is.na(l_3)] <- 0
h_1[is.na(h_1)] <- 0
h_2[is.na(h_2)] <- 0
h_3[is.na(h_3)] <- 0

l1 <- voi(data = l_1, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

l2 <- voi(data = l_2, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

l3 <- voi(data = l_3, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

h1 <- voi(data = h_1, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

h2 <- voi(data = h_2, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

h3 <- voi(data = h_3, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)





##############


l11 <- voi_1(data = l_1, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

l21 <- voi_1(data = l_2, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

l31 <- voi_1(data = l_3, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

h11 <- voi_1(data = h_1, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

h21 <- voi_1(data = h_2, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

h31 <- voi_1(data = h_3, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)



```




```{r}
(nv11|l1|h1) / (nv21|l2|h2) / (nv31|l3|h3)
```






```{r}
(nv1|l11|h11) / (nv2|l21|h21) / (nv3|l31|h31)
```

```{r}
source("R/voi_2.R")


c1_r1 <- ggplot(data = nv_1, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
  geom_point(aes(x=20, y=max(nv_1$prof_1, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_2, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_3, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_4, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_5, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
  
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_point(aes(x=20, y=max(nv_1$prof_1, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_2, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_3, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_4, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_1$prof_5, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+

  theme_minimal()+
    theme_minimal()+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))+
  theme(legend.position = "none", text = element_text(family = "Source Sans Pro"), plot.title = element_text(face = "bold"))




c1_r2 <- ggplot(data = nv_2, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
  geom_point(aes(x=20, y=max(nv_2$prof_1, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_2, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_3, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_4, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_5, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
  
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
   
    geom_point(aes(x=20, y=max(nv_2$prof_1, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_2, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_3, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_4, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_2$prof_5, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
  
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_2$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    theme_minimal()+
    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))+
  theme(legend.position = "none", text = element_text(family = "Source Sans Pro"), plot.title = element_text(face = "bold"))


c1_r3 <- ggplot(data = nv_3, aes(x = management_decision))+
  geom_line(aes(y=prof_1))+
  geom_line(aes(y=prof_2))+
  geom_line(aes(y=prof_3))+
  geom_line(aes(y=prof_4))+
  geom_line(aes(y=prof_5))+
  theme_minimal() +
  xlim(0, 125)+
  ylim(0, 105)+
  theme(axis.title = element_text(size = 8))+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)")+
   geom_point(aes(x=20, y=max(nv_3$prof_1, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_2, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_3, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_4, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_5, na.rm=TRUE)), color="#841F27", alpha = 0.05, shape = 15)+
  
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_1$prof_1, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_2, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_3, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
   
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_4, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
   
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_5, na.rm=TRUE)), color = "#841F27", linetype="dashed", alpha = 0.01)+
    
    geom_point(aes(x=20, y=max(nv_3$prof_1, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_2, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_3, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_4, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_point(aes(x=20, y=max(nv_3$prof_5, na.rm=TRUE)), color="#66b2b2", alpha = 0.05, shape = 15)+
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_1, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_2, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_3, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_4, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    geom_segment(aes(x = 20, y = 0, xend = 20, yend = max(nv_3$prof_5, na.rm=TRUE)), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
    
    theme_minimal()+

    labs(x = "Stocking Density (ind/m^3)",
         y = "Expected Profits ($)") + 
    xlim(0, 125)+
    ylim(0, 105)+
    theme(axis.title = element_text(size = 8))+
    theme(plot.title = element_text(size = 8))+
  theme(legend.position = "none", text = element_text(family = "Source Sans Pro"), plot.title = element_text(face = "bold"))





c2_r1 <- voi_2(data = l_1, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

c2_r2 <- voi_2(data = l_2, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

c2_r3 <- voi_2(data = l_3, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

c3_r1 <- voi_2(data = h_1, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

c3_r2 <- voi_2(data = h_2, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)

c3_r3 <- voi_2(data = h_3, 
    management_choice = "management_decision", 
    profits_E1 = "prof_1", 
    profits_E2 = "prof_2", 
    profits_E3 = "prof_3", 
    profits_E4 = "prof_4", 
    profits_E5 = "prof_5", 
    p1 = 0.2, p2 = 0.2, p3 = 0.2, p4 = 0.2, p5 = 0.2)


```




```{r}
(c1_r1|c2_r1|c3_r1) / (c1_r2|c2_r2|c3_r2) / (c1_r3|c2_r3|c3_r3)

ggsave("c1_r1.png", c1_r1, dpi=1200, bg = "transparent")
ggsave("c1_r2.png", c1_r2, dpi=1200, bg = "transparent")
ggsave("c1_r3.png", c1_r3, dpi=1200, bg = "transparent")
ggsave("c2_r1.png", c2_r1, dpi=1200, bg = "transparent")
ggsave("c2_r2.png", c2_r2, dpi=1200, bg = "transparent")
ggsave("c2_r3.png", c2_r3, dpi=1200, bg = "transparent")
ggsave("c3_r1.png", c3_r1, dpi=1200, bg = "transparent")
ggsave("c3_r2.png", c3_r2, dpi=1200, bg = "transparent")
ggsave("c3_r3.png", c3_r3, dpi=1200, bg = "transparent")




```






#Basic VoI Plots


```{r}
b1 <- ggplot(data = data, aes(x = management_decision))+
  geom_line(aes(y=prof_e_lo))+
  geom_line(aes(y=prof_e_hi))+
  geom_point(aes(x=12, y=9.295), color="#66b2b2", alpha = 0.05, shape = 15, size = 3)+
  geom_point(aes(x=20, y=20), color="#66b2b2", alpha = 0.05, shape = 15, size = 3, label = "point")+
  theme_minimal() +
  geom_text(aes(x = 27.5,y = 18, label= "High Temp. Scenario (50%)", hjust = 0),family = "Source Sans Pro", size = 3, color = "black")+
  geom_text(aes(x = 21,y = 5, label= "Low Temp. Scenario (50%)", hjust = 0),family = "Source Sans Pro", size = 3, color = "black")+
  
  geom_text(aes(x = -0.4,y = 9.295, label= "9", hjust = 1), size = 3, color = "black")+
  geom_text(aes(x = -0.4,y = 20, label= "20", hjust = 1), size = 3, color = "black")+
  
  geom_text(aes(y = -0.6,x = 20, label= "X2"), size = 3, color = "black")+
  geom_text(aes(y = -0.6,x = 12, label= "X1"), size = 3, color = "black")+
  
  geom_segment(aes(x = 12, y = 0, xend = 12, yend = 9.295), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 9.295, xend = 12, yend = 9.295), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 20, xend = 20, yend = 20), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 20, y = 0, xend = 20, yend = 20), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)",
       title = "Optimal stocking density with Perfect Information")+
   theme(legend.position = "none", text = element_text(family = "Source Sans Pro"), plot.title = element_text(face = "bold"))




```



```{r}

b2 <- ggplot(data = data, aes(x = management_decision))+
  geom_line(aes(y=prof_e_lo))+
  geom_line(aes(y=prof_e_hi))+
  geom_line(aes(y=prof_ave), color = "gray80")+
  geom_point(aes(x=15.746, y=13.757), color="#841F27", alpha = 0.05, shape = 15, size = 3)+
  theme_minimal() +
  geom_point(aes(x=15.746, y=19.095), color="#841F27", alpha = 0.05, shape = 15, size = 3)+
  theme_minimal() +
  geom_point(aes(x=15.746, y=8.389), color="#841F27", alpha = 0.05, shape = 15, size = 3)+
  theme_minimal() +
  geom_text(aes(x = 27.5,y = 18, label= "High Temp. Scenario (50%)", hjust = 0),family = "Source Sans Pro", size = 3, color = "black")+
  geom_text(aes(x = 21,y = 5, label= "Low Temp. Scenario (50%)", hjust = 0),family = "Source Sans Pro", size = 3, color = "black")+
  geom_text(aes(x = 18,y = 14, label= "Average Scenario", hjust = 0),family = "Source Sans Pro", size = 3, color = "gray80")+
  
  
    geom_text(aes(x = -0.4,y = 19.095, label= "19", hjust = 1), size = 3, color = "black")+
  geom_text(aes(y = -0.6,x = 15.746, label= "X*"), size = 3, color = "black")+
  geom_text(aes(x = -0.4,y = 8.389, label= "8", hjust = 1), size = 3, color = "black")+
  
  
  geom_segment(aes(x = 15.746, y = 0, xend = 15.746, yend = 19.095), color = "#841F27", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 19.095, xend = 15.746, yend = 19.095), color = "#841F27", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 8.389, xend = 15.746, yend = 8.389), color = "#841F27", linetype="dashed", alpha = 0.01)+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)",
       title = "Optimal stocking density with Uncertain Information")+
   theme(legend.position = "none", text = element_text(family = "Source Sans Pro"), plot.title = element_text(face = "bold"))





```

```{r}
b3 <- ggplot(data = data, aes(x = management_decision))+
  geom_line(aes(y=prof_e_lo))+
  geom_line(aes(y=prof_e_hi))+
  geom_line(aes(y=prof_ave), color = "gray80")+
  geom_point(aes(x=12, y=9.295), color="#66b2b2", alpha = 0.05, shape = 15, size = 3)+
  geom_point(aes(x=20, y=20), color="#66b2b2", alpha = 0.05, shape = 15, size = 3)+
  geom_point(aes(x=15.746, y=13.757), color="#841F27", alpha = 0.05, shape = 15, size = 3)+
  theme_minimal() +
  geom_point(aes(x=15.746, y=19.095), color="#841F27", alpha = 0.05, shape = 15, size = 3)+
  theme_minimal() +
  geom_point(aes(x=15.746, y=8.389), color="#841F27", alpha = 0.05, shape = 15, size = 3)+
  theme_minimal() +
  geom_text(aes(x = 27.5,y = 18, label= "High Temp. Scenario (50%)", hjust = 0),family = "Source Sans Pro", size = 3, color = "black")+
  geom_text(aes(x = 21,y = 5, label= "Low Temp. Scenario (50%)", hjust = 0),family = "Source Sans Pro", size = 3, color = "black")+
  geom_text(aes(x = 18,y = 14, label= "Average Scenario", hjust = 0),family = "Source Sans Pro", size = 3, color = "gray80")+
  geom_segment(aes(x = 15.746, y = 0, xend = 15.746, yend = 19.095), color = "#841F27", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 19.095, xend = 15.746, yend = 19.095), color = "#841F27", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 8.389, xend = 15.746, yend = 8.389), color = "#841F27", linetype="dashed", alpha = 0.01)+
  
    
    geom_text(aes(x = -0.4,y = 19.095, label= "19", hjust = 1), size = 3, color = "black")+
  geom_text(aes(y = -0.6,x = 15.746, label= "X*"), size = 3, color = "black")+
  geom_text(aes(x = -0.4,y = 8.389, label= "8", hjust = 1), size = 3, color = "black")+
    geom_text(aes(x = -0.4,y = 9.295, label= "9", hjust = 1), size = 3, color = "black")+
  geom_text(aes(x = -0.4,y = 20, label= "20", hjust = 1), size = 3, color = "black")+
  
  geom_text(aes(y = -0.6,x = 20, label= "X2"), size = 3, color = "black")+
  geom_text(aes(y = -0.6,x = 12, label= "X1"), size = 3, color = "black")+
  
  geom_segment(aes(x = 12, y = 0, xend = 12, yend = 9.295), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 9.295, xend = 12, yend = 9.295), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 0, y = 20, xend = 20, yend = 20), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  geom_segment(aes(x = 20, y = 0, xend = 20, yend = 20), color = "#66b2b2", linetype="dashed", alpha = 0.01)+
  labs(x = "Stocking Density (ind/m^3)",
       y = "Expected Profits ($)",
title = "Calculating the Value of Information")+
    theme(plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0))+
   theme(legend.position = "none", text = element_text(family = "Source Sans Pro"), plot.title = element_text(face = "bold"))
```

```{r}
ggsave("basic_1.png", b1, dpi=1200, bg = "transparent")
ggsave("basic_2.png", b2, dpi=1200, bg = "transparent")
ggsave("basic_3.png", b3, dpi=1200, bg = "transparent")
```

